### ISSUE TITLE
Fix doc claim that BOOST_PARSER_DEFINE_RULES is conditionally available

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#100]
The docs for `BOOST_PARSER_DEFINE_RULES` say:
> This macro is only available when the Boost.Preprocessor headers are available. 

[here](https://tzlaine.github.io/parser/doc/html/BOOST_PARSER_DEFINE_RULES.html)

So how do I define a rule in a stand-alone (non-Boost) version?

**Comment by tzlaine** [comment]
That's just a doc bug (cruft from a previous implementation).  It's always available now.
