### ISSUE TITLE
CMakeLists.txt is incompatible with Boost cmake

### ISSUE THREAD

**Issue by anarthal** [tzlaine/parser#127]
Guidelines listed here: https://github.com/boostorg/cmake/blob/develop/developer.md

I plugged Parser into Boost.MySQL CIs, some of which perform CMake workflow testing, and they failed. Note that Boost CIs don't generally have gtest installed on them (I don't know even if it's allowed due to licensing).

Build (edited link): https://drone.cpp.al/boostorg/mysql/545/7/3

**Comment by tzlaine** [comment]
The CMake files and all the test code is going to be tossed aside if/when the library is accepted.
