### ISSUE TITLE
Docs say 'define' when they probably meant to say 'declare'

### ISSUE THREAD

**Issue by LegalizeAdulthood** [tzlaine/parser#134]
At the top of the [tutorial page on rule parsers](https://tzlaine.github.io/parser/doc/html/boost_parser__proposed_/tutorial/rule_parsers.html):

> Here is how we define a [rule](https://tzlaine.github.io/parser/doc/html/boost/parser/rule.html), which is analogous to forward declaring a function:

This should say

> Here is how we declare a [rule](https://tzlaine.github.io/parser/doc/html/boost/parser/rule.html), which is analogous to forward declaring a function:

**Comment by tzlaine** [comment]
The line in question is this.

```c++
bp::rule<struct doubles, std::vector<double>> doubles = "doubles";
```

That is most definitely a declaration *and* a definition.
