### ISSUE TITLE
Docs say 'if' when they meant to say 'of'

### ISSUE THREAD

**Issue by LegalizeAdulthood** [tzlaine/parser#135]
On the page [Parsing in Detail](https://tzlaine.github.io/parser/doc/html/boost_parser__proposed_/tutorial/parsing_in_detail.html) the docs say:

> Control passes up to the parent if int_pair, +int_pair. 

they meant to say

> Control passes up to the parent of int_pair, +int_pair.

**Comment by tzlaine** [comment]
Thanks for pointing out all these typos!  These small mistakes are essentially invisible to me.   I'vebeen reading, re-reading, and editing these docs for weeks, and still missed all this stuff.  This and the other open issues are fixed on my mid-review branch.
