### ISSUE TITLE
Docs: is str_3 character range example correct?

### ISSUE THREAD

**Issue by LegalizeAdulthood** [tzlaine/parser#140]
On the page [The parse() API](https://tzlaine.github.io/parser/doc/html/boost_parser__proposed_/tutorial/the__parse____api.html), the code snippet in the second code block is given as:
```
char const * str_3 = "str";
auto result_3 = bp::parse(str_3 | boost::parser::as_utf16, p, bp::ws);
```
This is saying to parse the range of `char` characters as UTF-16?  Should this be `char16_t`?

**Comment by tzlaine** [comment]
No, the example is correct.  `str_3 | boost::parser::as_utf16` is a transcoding view that produces `char16_t`s.
