### ISSUE TITLE
Improve error reporting for `symbols`

### ISSUE THREAD

**Issue by AlexBAV** [tzlaine/parser#164]
Currently, if `symbols` parser is used as an expectation point and no value matches, something similar to the following is generated as an error message:

```cpp
symbols<EnumName> v { ... };

parse(r, "command1=" > v);
```

Generated error:

```
1:32: error: Expected symbols<enum EnumName>[<<action>>] here
```

Is it possible to provide a way to set a custom "error message", maybe by introducing a new `symbols` constructor overload (and/or a member function that can be called to set such a message)?

**Comment by tzlaine** [comment]
This is clearly an oversight no my part.  Thanks for pointing this out!

**Comment by AlexBAV** [comment]
That are really great news, thank you!
