### ISSUE TITLE
error: friend declaration with a constraint that depends on an enclosing template parameter must be a definition

### ISSUE THREAD

**Issue by intractabilis** [tzlaine/parser#169]
https://github.com/tzlaine/parser/blob/4cea9c03d6baf8165a21162e66be4f99ec85b529/include/boost/parser/detail/text/transcode_view.hpp#L178
Clang 18.1.4 with `-std=gnu++23` complains here that this friend function must be defined, not just declared. It seems correct according to [13.7.5 Friends](https://eel.is/c++draft/temp.friend#9).

**Comment by tzlaine** [comment]
Thanks for reporting this!

**Comment by intractabilis** [comment]
My pleasure. Great job with this library!
