### ISSUE TITLE
parser.hpp requires print_parser declaration for custom parsers

### ISSUE THREAD

**Issue by vmauery** [tzlaine/parser#178]
When I tried adding a print_parser for my custom parser, ultimately I had to add it before including parser.hpp like this:

```
namespace boost::parser
{
template <typename T>
struct custom_parser;
namespace detail
{
template <typename Context, typename T>
void print_parser(Context const& context, custom_parser<T> const&,
                  std::ostream&, int components = 0);
} // namespace detail
} // namespace boost::parser

#include <boost/parser/parser.hpp>
```

And then I could define it later after my parser class. Also, I didn't see anything in the documentation about adding a parser_interface and only managed to find that by reading through other parsers in the parser.hpp file.

I think this could be avoided by adding a default noop print_parser (not sure what this is used for anyway). Or maybe being able to turn this feature off would be good.

```
template <typename Context>
void print_parser(Context const&, auto const&, std::ostream&, int component = 0)
{
}
```

**Comment by tzlaine** [comment]
This is by design.  The ability to be able to trace your parse is essential to writing anything but the simplest of parsers.  When you add a new custom parser, it is expected that you also add a function that enables its instrumentation.  If you make that a noop, well, "bad programmer!"

**Comment by jonesmz** [comment]
This is not a good design. I've spent hours trying to figure out why declaring 

```
namespace boost::parser::detail
{

/// Required by Boost.Parser's error reporting infrastructure.
template<typename CONTEXT_T, typename STR_ITER_T, typename STR_SENTINEL_T>
void print_parser(...);
```

after my parser isn't working.

the lookup for `print_parser` should be an ADL lookup hook, and not dependent on fragile and undocumented specific behavior like needing to define the printer in a special order relative to #include statements.

The tutorial does say that `print_parser` must be defined, but makes no mention of the special include ordering requirements. I don't care about needing to define the printer, it's the lack of real ADL lookup that's the bad design.
