### ISSUE TITLE
Build fails when no boost::variant2

### ISSUE THREAD

**Issue by isominsky** [tzlaine/parser#179]
diff --git a/test/tuple_aggregate.cpp b/test/tuple_aggregate.cpp
index fc6af6f7..3effce66 100644
--- a/test/tuple_aggregate.cpp
+++ b/test/tuple_aggregate.cpp
@@ -81,7 +81,7 @@ struct s1_boost_variant
     std::vector<int> vec_;
 };
 #endif
-#if TEST_BOOST_VARIANT
+#if TEST_BOOST_VARIANT2
 struct s1_boost_variant2
 {
     int i_;

**Comment by tzlaine** [comment]
Thanks!  Classic copy pasta.
