### ISSUE TITLE
Consider adding allocator support

### ISSUE THREAD

**Issue by eterchun** [tzlaine/parser#184]
One of the apparent benefits of a library like lexy over the current spirit libraries is that lexy supports allocators via the built-in types (e.g., [for containers](https://lexy.foonathan.net/reference/callback/container/#as_list) and [for strings](https://lexy.foonathan.net/reference/callback/string/#as_string)). Based on the current documentation, it appears the intention is [not to support allocators in Boost.Parser](https://tzlaine.github.io/parser/doc/html/boost_parser__proposed_/tutorial/memory_allocation.html). However, it seems that the current design could instead support custom allocators, for example via globals or perhaps parameters.

**Comment by tzlaine** [comment]
Allocators suck.  I won't be doing this.  However, you can use your own containers with your own custom allocators, and parse into them.  For instance, parsing into a `pmr::vector<pmr::vector<...>>`.
