### ISSUE TITLE
docs: provide an example of parsing into UDTs

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#28]
Boost.Spirit docs show an example of how to parse into user-defined structs:
https://www.boost.org/doc/libs/1_84_0/libs/spirit/doc/html/spirit/qi/tutorials/employee___parsing_into_structs.html

Provide a similar example in the docs for Boost.Parser.

**Comment by tzlaine** [comment]
Thanks for pointing this out.  I'll add one.
