### ISSUE TITLE
Truncaiton warning in `transcode_iterator.hpp`

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#29]
On MSVC I get warning C4244 when compiling line
https://github.com/tzlaine/parser/blob/master/include/boost/parser/detail/text/transcode_iterator.hpp#L3147
due to conversion from `ptrdiff_t` do `uint8_t`.

**Comment by akrzemi1** [comment]
Similarly in
https://github.com/tzlaine/parser/blob/master/include/boost/parser/detail/text/transcode_iterator.hpp#L2854

This happens when compiling example https://github.com/tzlaine/parser/blob/master/example/hello.cpp

**Comment by tzlaine** [comment]
The fixes for this are harmless, so I've implemented them.  However, neither of these warnings is legit.  In both cases, you know either know statically (the second one), or from the type's invariants (the first one) that the value will always be representable in the assignee.  This is why I always aim for warning-free GCC and Clang builds, and then basically ignore hte MSVC warnings. :)
