### ISSUE TITLE
Consider using Boost.PFR

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#33]
[Boost.PFR](https://www.boost.org/doc/libs/1_84_0/doc/html/boost_pfr.html) allows tuple-like access to aggregate types without the need to use any "ADAPT" macro. In my parser use cases I use aggregates for representing sequences, and would benefit from not having to use those macros.

Downsides:
* another Boost dependency
* slower compile times
* compile errors from Boost.PFR will show up as errors from Boost.Parser.

Feel free to close this issue at any time. This is just a suggestion.

**Comment by tzlaine** [comment]
I already had this idea to make the example from #28 Easier to write, but I couldn't remember the name PFR!  So, thanks for saving me a lot of searching.  I decided to reimplement the bits of it that I needed.
