### ISSUE TITLE
typo in the docs "Ready" instead of "read"

### ISSUE THREAD

**Issue by mclow** [tzlaine/parser#38]
https://tzlaine.github.io/parser/doc/html/boost_parser__proposed_/this_library_s_relationship_to_boost_spirit.html says:

> If you are familiar with Spirit 2 and/or Spirit X3, you may be interested in this section. If you are not, and you have not ready the tutorial for Boost.Parser yet, very little of this will make sense.

Should probably says "have not read".

**Comment by tzlaine** [comment]
Yup.  That's wrong.  Thanks!
