### ISSUE TITLE
Docs: what is a parser?

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#41]
In Boost.Parser, what is considered a parser? Is it:
* a type that derives from `parser_interface`?
* any type that has the required interface? 

It looks like it is the former. I recommend devoting a section to Parser. It would say:
* that a parser is a _CRTP-specialization of_ `parser_interface`,
* when (if) one has to provide their own CRTP-specialization
* what the iterface of `parser_interface` is.

**Comment by akrzemi1** [comment]
Can you specify what it means to be a parser as a c++ concept (even if you do not use concepts in the implementation)?

If I define a class that only has the two call operators and nothing else, will it work as a parser with your library?

**Comment by akrzemi1** [comment]
It looks to me that when I need to create a parser:
* I must declare the two function call operators, and
* I mast inherit from `parser_interface`.

**Comment by akrzemi1** [comment]
In section [Parsing In Detail](https://tzlaine.github.io/parser/doc/html/boost_parser__proposed_/tutorial/parsing_in_detail.html), I do not understand this sentence:

> Step 1) The input is "1 2 3", and the stack of active parsers is `int_pairs_plus` -> `+int_pair` -> `int_pair` -> `bp::int_`. 

Is this a mistake? Or is it correct? But what does the arrow represent here? Does this mean a four-element stack?

**Comment by tzlaine** [comment]
> In section [Parsing In Detail](https://tzlaine.github.io/parser/doc/html/boost_parser__proposed_/tutorial/parsing_in_detail.html), I do not understand this sentence:
> 
> > Step 1) The input is "1 2 3", and the stack of active parsers is `int_pairs_plus` -> `+int_pair` -> `int_pair` -> `bp::int_`.
> 
> Is this a mistake? Or is it correct? But what does the arrow represent here? Does this mean a four-element stack?

Yes, this is right.  I'll add more text to make it clearer what I mean.  Bascially, since each parser is a callable, there is a stack of parsers from the top-level one down to the current parser.

**Comment by tzlaine** [comment]
> In section [Parsing In Detail](https://tzlaine.github.io/parser/doc/html/boost_parser__proposed_/tutorial/parsing_in_detail.html), I do not understand this sentence:
> 
> > Step 1) The input is "1 2 3", and the stack of active parsers is `int_pairs_plus` -> `+int_pair` -> `int_pair` -> `bp::int_`.
> 
> Is this a mistake? Or is it correct? But what does the arrow represent here? Does this mean a four-element stack?

Add a separate issue for this.
