### ISSUE TITLE
Cleaner description of attribute combination

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#62]
The table in [Combining Operations](https://tzlaine.github.io/parser/doc/html/boost_parser__proposed_/tutorial/combining_operations.html) implies that the attribute of `(int_ % ',') | attr(std::vector<int>{})`  would be `std::variant<std::vector<int>, std::vector<int>>`. But it isn't due to special rules. While these special rules are described in [Parser attributes](https://tzlaine.github.io/parser/doc/html/boost_parser__proposed_/tutorial/attribute_generation.html#boost_parser__proposed_.tutorial.attribute_generation.parser_attributes), we cannot see them from the Table 1.2. (Combining Operations and Their Semantics)

**Comment by tzlaine** [comment]
Ah, thanks,  I plain forgot to mention that.
