### ISSUE TITLE
A single-header version?

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#70]
Would it be possible to also ship a single-header version of this library?
Such header-only variants make it so easy to test and demo such library in Compiler Explorer. Especially useful in a work envireonment when one is not allowed to download or use or install practically anything.

**Comment by akrzemi1** [comment]
Ok, I found a tool to do it myself: https://pypi.org/project/pcpp
Now I can test the library with Compiler Explorer: https://godbolt.org/z/Y4fEWhrbo
Still, you might consider providing such a "combined header" for easy online testing.

**Comment by tzlaine** [comment]
Interesting!  I think I'll try to set this up as a Github action, pushing to a branch.  I think this would be very nice to have if its creation could be automated.
