### ISSUE TITLE
How to define a rule parser with an empty attribute?

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#75]
The docs do not state it clearly, how I can define a rule parser with an empty attribute (e.g., when I need a parser for skipping comments). Neither in the tutorial, nor in the reference section?

I am guessing that I need to skip the second template parameter. Is that right?

**Comment by tzlaine** [comment]
Yes, that's right.  I'll add this to the docs in a way that's more clear.  I swear it *used* to say that....
