### ISSUE TITLE
state of the output argument upon unsuccessful parse

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#78]
The docs should document that upon unsuccessful parse the value of the output parameter (where the result is supposed to be written) is in an unspecified state (potentially changed).

An example illustrating this:
https://godbolt.org/z/a5vb8E87o

**Comment by tzlaine** [comment]
Will do.

**Comment by tzlaine** [comment]
I rethought this.  Instead of just documenting the behavior, I made the `parse()` API clear the out-param on failure (via `attr = Attr()`).  This is more consistent with what parsers do; when they fail, they do `attr = Attr()`.
