### ISSUE TITLE
Clang compiler warnings

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#87]
The usage of "expectation" operator and and a sequence operator in one parser causes warnings to be displayed about the operator precedence:

https://godbolt.org/z/xxGc8jod3

Even without `-Wall`. 
I know that it is difficult to do something about it. Maybe clang should be contacted to stop warning about the operator precedence for user provided operators? Or parser classes need to be tagged in a way clang understands.

**Comment by tzlaine** [comment]
There's nothing I can do about this.  You can parenthesize the expression however you like, and it will not change its meaning.  You can also push/pop warning disablements.

**Comment by akrzemi1** [comment]
FYI:
https://github.com/llvm/llvm-project/issues/80538
