### ISSUE TITLE
Add `enable_variant`?

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#88]
Is it possible to add a customization point that would make Boost.Parser recognize `boost::variant` as a variant type?
In a similar vein as `enable_optional` works.

**Comment by tzlaine** [comment]
Enable optional is necessary, because I need to know if a particular value os optional-wrapped or not.  Not so for variants.  This just works already.  There are even tests for it.  See https://github.com/tzlaine/parser/blob/master/test/tuple_aggregate.cpp .

**Comment by akrzemi1** [comment]
However,  this seems to break on more complicated cases. The following program does not compile.
https://godbolt.org/z/93ddv1To9

But when I switch to `std::variant` from `boost::variant` at line 10. It starts working.

**Comment by tzlaine** [comment]
Interesting!  Ok, I'll investigate.

**Comment by tzlaine** [comment]
So, there are only 4 errors, and they're all this one or a cascade from this one:

```
boost/variant/detail/variant_io.hpp:64:14: error: no match for 'operator<<' (operand types are 'std::basic_ostream<char>' and 'const std::vector<SingleRedirection>')
   64 |         out_ << operand;
      |         ~~~~~^~~~~~~~~~
```

This has zero to do with Boost.Parser.  It has to do with Boost.Variant's `op<<`, `std::vector`, and your type.  Am I missing something?

**Comment by akrzemi1** [comment]
But why would `parse` require an `op<<` of its targer?

**Comment by akrzemi1** [comment]
Or rather, the question should be why Boost.Parser wants to use `op<<` for `boost::variant` but doesn't want to use it for `std::variant`?

Here's a reduced example: https://godbolt.org/z/rsW4jd1Kd

**Comment by tzlaine** [comment]
Ah, damn.  You're right.  There is one place that is using an `is_variant` trait, and it's in the printing.  Ok, I'll have to add `enable_variant` after all.
