### ISSUE TITLE
Request: a better example in `replace` documentation

### ISSUE THREAD

**Issue by akrzemi1** [tzlaine/parser#96]
Can wee see a motivating use case for `replace`?

The description in the docs:
https://tzlaine.github.io/parser/doc/html/boost_parser__proposed_/tutorial/algorithms_and_views_that_use_parsers.html#boost_parser__proposed_.tutorial.algorithms_and_views_that_use_parsers._globalname_alt__boost__parser__replace___code__phrase_role__identifier__boost__phrase__phrase_role__special______phrase__phrase_role__identifier__parser__phrase__phrase_role__special______phrase__phrase_role__identifier__replace__phrase___code___globalname_

Doesn't give a hint why anyone would need this feature for.

The example with `bp::lit("XYZ")` isn't very convincing. It looks like `replace` for strings would be better.

Is there a real life use case for this that we could see?

**Comment by tzlaine** [comment]
You really want me to justify the utility of string replacement?

**Comment by akrzemi1** [comment]
The docs need to give an example anyway. I think demonstrating a parser that is a `bp::lit` is not the best choice: there are simpler ways to replace one string literal with another. 
Maybe instead an example that erases the card numbers:

```c++
auto card_number = bp::repeat(4)[bp::int_] >> bp::repeat(3)['-' >> bp::repeat(4)[bp::int_]];
auto card_number_wipe = bp::replace(card_number , "XXXX-XXXX-XXXX-XXXX");
```

**Comment by tzlaine** [comment]
Ok, I see.  Yeah, that's a much better example.  I'll change this.
